### ISSUE TITLE
有些疑问问一下

### ISSUE THREAD

**Issue by Lelight-Iot** [tuya/tuya-iotos-android-gateway-demo#5]
应用在平板主机，主机本身接入了tuyahomesdk，网关启动后，如何让网关与当前家庭绑定，还需要自己发现自己，然后绑定？感觉有点绕弯子，有没有获取token，然后直接让网关绑定的接口？如果现在没有，有开放的可能性吗？

**Comment by mimimumu** [comment]
## 网关激活

启动网关成功之后，才可以入网。

### 获取激活 token

开始配网之前，SDK 需要在联网状态下从涂鸦云获取配网 Token，Token 的有效期为 10 分钟，且配置成功后就会失效（再次配网需要重新获取）。

```java
TuyaHomeSdk.getActivatorInstance().getActivatorToken(homeId,
		new ITuyaActivatorGetToken() {

			@Override
			public void onSuccess(String token) {

			}

			@Override
			public void onFailure(String s, String s1) {

			}
		});
```

**参数说明**

| 参数   | 说明                                                         |
| :----- | :----------------------------------------------------------- |
| homeId | 家庭 ID，从用户信息中获取，参考：二维码授权登录 -  获取登录状态 章节 |

### 激活网关

**接口说明**

```java
public int tuyaIotBindToken(String token);
```

**参数说明**

| 参数  | 说明       |
| ----- | ---------- |
| token | 入网 token |

**返回值说明**

| 返回值  | 说明                                                         |
| ------- | ------------------------------------------------------------ |
| 0       | 调用成功，请注意，调用成功不代表已经入网成功，入网结果通过 onNetworkStatus 通知。 |
| 非 0 值 | 调用失败，没有入网。                                         |

激活成功后在网关状态回调 接口中有回调

**Comment by Lelight-Iot** [comment]
@mimimumu 请问extension_sdk和networking_sdk区别是什么？我这个问题没说清楚，在networking_sdk中好像没有类似的接口可以直接通过token激活网关的
