### ISSUE TITLE
networking_sdk的一些疑问

### ISSUE THREAD

**Issue by Lelight-Iot** [tuya/tuya-iotos-android-gateway-demo#6]
因为项目需求，只有用下面这个sdk才能满足需求（需要上报子设备，管理，控制的接口）
implementation 'com.tuya.smart:tuyasmart-gw_networking_sdk:1.0.9'

对应的文档是
https://github.com/chenglei110/tuya-iotos-android-gateway-demo/blob/networking_sdk/README_cn.md
请问这个网关sdk你们还有在维护吗（或者有没有新的替代sdk）?
目前测出一下问题，请问是工单提问，还是提issues与你们沟通
1. 绑定网关后，调用 deviceOnlineStatusUpdate 更新子设备在线状态，但是app的子设备并没有在线，需要把应用重启才可以
2. 有没有直接通过token绑定的接口（目前没看到有，可否考虑开放）

**Comment by chenglei110** [comment]
您好，是在维护的。

第一个问题：用户配置了心跳是通过心跳机制来保证的，如果没有那个才会又用。
第二个问题：内部有接口，但没有开发给客户，客户需要只能定制。
